### ISSUE TITLE
Interface for filter overrides

### ISSUE THREAD

**Issue by jmcarp** [jmcarp/filteralchemy#1]
Currently, `FilterSet` generates a filter for each model field and for each operator. To override, users have to declare additional filters for a field:

``` python
class MyFilterSet(FilterSet):
    class Meta:
        model = MyModel
        operators = (Equal, In)
    column__gt = Filter('column', fields.Int(), operator=Greater)
    column__lt = Filter('column', fields.Int(), operator=Less)
```

To reduce boilerplate, it would be helpful to specify operator patterns per column in `Meta`:

``` python
class MyFilterSet(FilterSet):
    class Meta:
        model = MyModel
        operators = (Equal, In)
        column_operators = {
            'column': [Greater, Less],
        }
```

It might be useful to specify other overrides as well. This could be done via extra `Meta` options, such as `column_fields`, etc., or by combining all overrides into a single `column_overrides` dict:

``` python
column_overrides = {
    'column': {
        {
            'operators': [Greater, Less],
            'field': fields.Float(),
        },
    }
}
```

Last thought: instead of specifying overrides for groups of filters in `Meta`, I was also thinking about introducing a `FilterFactory` that can be declared in a `FilterSet`:

``` python
class MyFilterSet(FilterSet):
    class Meta:
        model = MyModel
        operators = (Equal, In)
    column_filters = FilterFactory('column', fields.Float(), operators=(Equal, Greater, Less))
```

I'm leaning towards separate `column_operators` and `column_fields` options in `Meta`--I think it's simpler if class variables are all `Filter` declarations, and all the options for auto-generating filters live in `Meta`. Any preferences @sloria?

**Comment by sloria** [comment]
> I think it's simpler if class variables are all Filter declarations, and all the options for auto-generating filters live in Meta.

+1. 

I think either of the first two options you have above is fine. `column_overrides` seems a bit more future-proof. Also, it's nice to minimize the number of `class Meta` options users will need to remember for typical usage.
